### ISSUE TITLE
Link to wrong commit

### ISSUE THREAD

**Issue by dangerousbeans** [rhgraysonii/volt_tutorial#3]
Hey there, just working through your awesome tutorial and noticed one of the commit links goes to a weird place: have a look at this guy:

https://github.com/rhgraysonii/volt_tutorial/blob/master/part_3.md#commit-773b4825ed70acf97d3b8a82e5b7bf57115ad89f

**Comment by ybur-yug** [comment]
Thanks! Almost definitely me copy-pasting far too late at night. I'm AFK atm but will look into it ASAP tmrw

**Comment by ybur-yug** [comment]
Could you please specify the document that commit is linked to in @dangerousbeans ? (on mobile atm)

**Comment by ybur-yug** [comment]
No worries I'll grep it out when im home via the link if you dont respond, just trying to be lazy :P

**Comment by ybur-yug** [comment]
should be fixed in latest version
