### ISSUE TITLE
Interesting, thoughts for opal-phaser-examples?

### ISSUE THREAD

**Issue by ylluminate** [rhgraysonii/volt_tutorial#4]
Thanks for your beginning of the tutorial here.  We've been using Sinatra just to rough things out for [`opal-phaser`](https://github.com/orbitalimpact/opal-phaser-examples), but I got to thinking maybe we should give `volt` a little more facetime with our efforts.  Admitting that I haven't had time to dig into `volt` yet, could you give a quick tip on how you might consider framing the examples that we're putting together within the `volt` framework?  Right now it's been pretty much just running a config.ru in each example folder so that as you're going through it, you just `bundle exec rackup` to get your context, but ultimately we're going to flesh this out much more so that it's on our own website and thus `volt` should serve us better in that regard.

At any rate, was hoping you could give some tips to perhaps use `volt` in a dirty way initially here or offer some advice on restructuring the current project to be more conducive for building it out with `volt` tying it together.

**Comment by ybur-yug** [comment]
Honestly the framework is too young and I've not enough context to truly answer this question with any justice. If you can flesh our specific needs/goals I can help more. bobbygrayson[at]gmail[dot]com
