### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by heri** [rhgraysonii/volt_tutorial#8]
Good intro. Links are missing, and also subtitles would be great.

**Comment by ybur-yug** [comment]
Can you elaborate on what you mean by links?

**Comment by heri** [comment]
Links in part_1.md:
This is a rough retelling of @ryanstout
https://github.com/ybur-yug/volt_tutorial/blob/master/link'
The Pragmatic Programmer
https://github.com/ybur-yug/volt_tutorial/blob/master/link said
How is the frontend JavaScript removed? Opal
https://github.com/ybur-yug/volt_tutorial/blob/master/link.

On Sun, Jul 19, 2015 at 6:11 PM, yburyug notifications@github.com wrote:

> Can you elaborate on what you mean by links?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ybur-yug/volt_tutorial/issues/8#issuecomment-122710460
> .

## 

I write at Medium http://medium.com/@heri - I code
http://github.com/heri - I take pictures
https://www.flickr.com/photos/heri_quebec/ - I tweet
http://twitter.com/heri

**Comment by ybur-yug** [comment]
Thanks! Sorry, yeah `(link)` is what I have been using for filler. These are fixed in the current version I have local that I've not pushed up (like I said prior, I'm waiting for 1.0 to do the next release since there have been a good amount of API changes soince 0.9.2). So duly noted, but I'm going to close this even though its not in the official repo.

**Comment by ybur-yug** [comment]
@heri if you find anything else thats tertiary to this feel free to open another though. Also, for more 'current' workings of Volt definitely check out Rick Carlino's tutorials on [Data Melon](http://datamelon.io)'s blog! More current.

**Comment by ybur-yug** [comment]
Woops accidentally reopened it. I'm smart. And tired. Heh. Sorry (again).

**Comment by heri** [comment]
all good

if you need help, let me know. I'm a beginner with volt but good in rails.

On Sun, Jul 19, 2015 at 11:10 PM, yburyug notifications@github.com wrote:

> Woops accidentally reopened it. I'm smart. And tired. Heh. Sorry (again).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ybur-yug/volt_tutorial/issues/8#issuecomment-122742881
> .

## 

I write at Medium http://medium.com/@heri - I code
http://github.com/heri - I take pictures
https://www.flickr.com/photos/heri_quebec/ - I tweet
http://twitter.com/heri
